---
title: "rist_for_jared"
author: "Sam Struthers"
date: "`r Sys.Date()`"
output: html_document
---

## sourcing and packages 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)


try(plyr::ldply(list.files(path="src/",
                           pattern="*.R",
                           full.names=TRUE),
                source))

```



# Grab cleaned

```{r}

rist_cleaned <- feather::read_feather('data/pretty/all_data_15min.feather')%>%
  filter(site %in% c("rist", "legacy") )
```

## Grab Raw

```{r}

pre_2022 <- read_csv('data/pretty/all_sensor_data_pre2022.csv') %>%
  mutate(site = tolower(sensor)) %>%
  rename(pH1 = pH,
         comment_pre = comments) %>%
  select(-c(sensor, year, date, data))

field_notes <- readxl::read_excel('data/sensor_field_notes.xlsx') %>%
  mutate(DT = (paste0(date, " ", start_time_mst))) %>%
  mutate(DT = ymd_hm(DT)) %>%
  arrange(DT) %>%
  mutate(DT = round_date(DT, "15 minutes"))

cal_table <- cal_tabler()


rist_raw <- going_rawless(site_name = "rist", trolled = NA) %>%
  mutate(DT = ymd_hms(DT)) %>%
  # Dataset got swapped to Rist's sensor, so need to remove data that 
  # is actually Rist. Sensor also capped from 5/6/2022 - 5/9/2022 (flow too low)
  filter(ymd_hms(DT) <= ymd_hms("2022-05-30 09:00:00")) %>%
  filter(!(ymd_hms(DT) >= ymd_hms('2022-05-06 12:00:00') & ymd_hms(DT) <= ymd_hms('2022-05-09 14:30:00'))) %>%
  padr::pad(by = 'DT') %>%
  # Link up calibration data:
  full_join(na.locf(na.locf(filter(cal_table, site == "rist")), fromLast = TRUE), 
            by = c('site','DT'))


```


## SC plot

```{r pressure, echo=FALSE}

SC <- ggplot()+
  geom_line(data = rist_cleaned,aes(x=DT , y= Specific_Conductivity_µS_cm, group = site, color = site))+
  theme_bw()

plotly::ggplotly(SC)


```


## Temp plot

```{r pressure, echo=FALSE}

temp <- ggplot()+
  geom_line(data = rist_cleaned,aes(x=DT , y= Temperature_C, group = site, color = site))+
  theme_bw()

plotly::ggplotly(temp)


```


## Depth plot

```{r pressure, echo=FALSE}

depth <- ggplot()+
  geom_line(data = rist_cleaned,aes(x=DT , y= Depth_ft, group = site, color = site))+
  theme_bw()

plotly::ggplotly(depth)


```
## Export Data

```{r}

rist_for_jared <- rist_cleaned%>%
  filter(site == "rist")%>%
  mutate(date = as_date(DT), 
         hour = lubridate::hour(DT), 
         minute = lubridate::minute(DT))%>%
  select(DT,date, hour, minute, site , Temperature_C, Specific_Conductivity_µS_cm, Depth_ft)

names(rist_for_jared)
unique(rist_for_jared$site)

arrow::write_csv_arrow(rist_for_jared,file = "data/sharing/rist_sc_temp_depth.csv" )



```

# Turb Threshold calculating

```{r}
library(tidyverse)
library(ggplot2)
library(arrow)


all_data_15min <- read_feather(file = "data/pretty/all_data_15min.feather")

unique(all_data_15min$site)

archery <- filter(all_data_15min, site == "archery")
elc <- filter(all_data_15min, site == "elc")


ggplot(filter(all_data_15min, site %in% c("elc","timberline", "legacy")), aes(x = DT, y = Turbidity_NTU, color = site))+
  geom_line()

ggplot(elc, aes(x = DT, y = Turbidity_NTU))+
  geom_line()

timberline_turb <- filter(all_data_15min, site == "timberline"& Turbidity_NTU != "NaN")%>%
  select(DT, Turbidity_NTU)

write_csv_arrow(timberline_turb, sink = "data/sharing/threshold_calc/timberline_turb.csv")


get_turb <- function(site_name){
  turb <- filter(all_data_15min, site == site_name & Turbidity_NTU != "NaN")%>%
  select(DT, Turbidity_NTU)%>%
    mutate(datetime = str_sub(as.character(DT), end = -4), 
           cleaned_date = format(DT, "%m/%d/%Y %H:%M"))%>%
    select(DT, cleaned_date,Turbidity_NTU)
  return(turb)
  #write_csv_arrow(turb, sink = paste0("data/sharing/threshold_calc/",  site_name,  "_turb.csv"))
}


#get_turb(site_name = "timberline")
#get_turb(site_name = "elc")
#get_turb(site_name = "archery")
#get_turb(site_name = "legacy")



```
## In house threshold calculator

```{r}
# preform t tests
#warning = 95%
# alarm = 99%

# preform a two-tailed inverse of the Student's t-distribution to find the critical value for the t-test

get_thresholds <- function(sites, conf){
  
turb <- get_turb(site_name = sites)

alpha <- 1-conf # significance level
n <- nrow(turb) # sample size
df <- n - 1  # degrees of freedom
t_value <- qt(1 - alpha / 2, df)  # two-tailed inverse for conf interval


sd <- sd(turb$Turbidity_NTU)
mu <-mean(turb$Turbidity_NTU)
site_threshold <- tibble(site_name  = sites, 
                         confidence_int = conf)%>%
  mutate(threshold_value = mu+(sd*t_value))


return(site_threshold)
}
 
sites <- c("elc", "timberline", "archery", "legacy")
conf1<- .95
conf2 <- .99

# map over site and conf using the get_thresholds function
conf1_thresholds <- map2(sites, conf1, get_thresholds)%>%
  list_rbind()

thresholds_turb <- map2(sites, conf2, get_thresholds)%>%
  list_rbind()%>%
  rbind(conf1_thresholds)%>%
  pivot_wider(names_from = confidence_int, values_from = threshold_value)%>%
  select(site = site_name, warning = `0.95`, alarm =`0.99`)


```




## Turbidity Thresholds Calculated:

```{r}

some_turb <- filter(all_data_15min, site %in% c("elc","timberline","archery", "legacy")& Turbidity_NTU != "NaN")%>%
  select(site, DT, Turbidity_NTU)%>%
  left_join(thresholds_turb, by = "site")%>%
  mutate(warning_trigger = ifelse(Turbidity_NTU >= warning, T,F), 
         alarm_trigger = ifelse(Turbidity_NTU >= alarm, T, F), 
         #make a column using case_when() named trigger and it is equal to Alarm if alarm trigger is true, warning if warning trigger is true, and none if neither are true
          trigger = case_when(alarm_trigger == T ~ "Alarm", 
                              warning_trigger == T ~ "Warning", 
                              T ~ "None"))


# make a graph of DT and Turbidity_NTU and color by trigger. Also display the warning and alarm thresholds for each site. facet wrap by site
#  make alarm values Red and warning values orange, none values black
#order the triggers so that alarm is first, warning is second, and none is last
# include the month and year in the x axis labels
# rename the legend to "Turbidity Trigger" and ylab to "Turbidity (NTU)"
# make the title "Turbidity Triggers for ELC, Timberline, Archery, and Legacy"
 some_turb$trigger <- factor(some_turb$trigger, levels = c("Alarm", "Warning", "None"))
ggplot(some_turb, aes(x = DT, y = Turbidity_NTU, color = trigger))+
  geom_point()+
  #make a dashed horizontal line equal to the value of warning for each site
 geom_hline(aes(yintercept = warning),color = "grey", linetype = "dashed")+
  geom_hline(aes(yintercept = alarm),color = "black",  linetype = "dashed")+
  facet_wrap(~site)+
  theme_bw(base_size = 24)+
  scale_color_manual(values = c("red", "orange", "black"))+
  #rename the legend to "Turbidity Trigger" and ylab to "Turbidity (NTU)"
  labs(color = "Turbidity Trigger",
       y = "Turbidity (NTU)")+
  # make the title "Turbidity Triggers for ELC, Timberline, Archery, and Legacy"
  ggtitle("Turbidity Triggers for ELC, Timberline, Archery, and Legacy")+
  # include the month and year in the x axis labels
  scale_x_datetime(date_labels = "%m/%Y", date_breaks = "6 month")

 ggsave(filename = "data/sharing/threshold_calc/turb_warning_alarm_graph.jpg", width = 30, height = 14, dpi = 300)
 
 some_turb_summary <- some_turb%>%
   group_by(site, trigger)%>%
   summarise(count = n())%>%
   pivot_wider(names_from = trigger, values_from = count)%>%
    mutate(total = Alarm + Warning + None)
```
### Single site plots
```{r}

indv_plot <- function(site_choice){
ggplot(filter(some_turb, site == site_choice), aes(x = DT, y = Turbidity_NTU, color = trigger))+
  geom_point()+
  #make a dashed horizontal line equal to the value of warning for each site
  geom_hline(aes(yintercept = warning),color = "grey", linetype = "dashed")+
  geom_hline(aes(yintercept = alarm),color = "black",  linetype = "dashed")+
  theme_bw(base_size = 24)+
  scale_color_manual(values = c("red", "orange", "black"))+
  #rename the legend to "Turbidity Trigger" and ylab to "Turbidity (NTU)"
  labs(color = "Turbidity Trigger",
       y = "Turbidity (NTU)")+
  # make the title "Turbidity Triggers for ELC, Timberline, Archery, and Legacy"
  ggtitle(paste0("Turbidity Triggers for ", site_choice))+
  # include the month and year in the x axis labels
  scale_x_datetime(date_labels = "%m/%Y", date_breaks = "6 month")

 ggsave(filename = paste0("data/sharing/threshold_calc/", site_choice,"_turb_warning_alarm_graph.jpg"), width = 30, height = 14, dpi = 300)
}
map(sites, indv_plot)

```



### Reducing triggers


```{r}

    #make a new dataframe named some_turb_reduced that only has the columns DT, Turbidity_NTU, trigger, and site
    some_turb_reduced <- some_turb%>%
      select(DT, Turbidity_NTU, trigger, site, warning, alarm)
      #arrange by site and DT
      some_turb_reduced <- arrange(some_turb_reduced, site, DT)%>%
        mutate(trigger_reduced = NA)
      #loop over this dataframe and add a column named trigger_reduced that is equal to alarm only if the trigger value of the previous row is none or warning and the trigger value of the current row is alarm. Otherwise, it is equal to the trigger value of the current row unless it is alarm, in which case it is equal to Alarm-no message
      for(i in 2:nrow(some_turb_reduced)){
        if(some_turb_reduced$trigger[i] == "Alarm" & some_turb_reduced$trigger[i-1] != "Alarm"){
          some_turb_reduced$trigger_reduced[i] = "Alarm"
        }else{
         if(some_turb_reduced$trigger[i] == "Alarm" & some_turb_reduced$trigger[i-1] == "Alarm"){
          some_turb_reduced$trigger_reduced[i] = "Alarm_no_message"
        }else{
          some_turb_reduced$trigger_reduced[i] = as.character(some_turb_reduced$trigger[i])
        }
        }
      }
      
      
some_turb_reduced_summary <- some_turb_reduced%>%
   group_by(site, trigger_reduced)%>%
   summarise(count = n())%>%
   pivot_wider(names_from = trigger_reduced, values_from = count)%>%
    mutate(total = Alarm + Alarm_no_message+ Warning + None)
 
 some_turb_reduced$trigger_reduced <- factor(some_turb_reduced$trigger_reduced, levels = c("Alarm","Alarm_no_message", "Warning", "None"))
ggplot( some_turb_reduced, aes(x = DT, y = Turbidity_NTU, color = trigger_reduced))+
  geom_point()+
  #make a dashed horizontal line equal to the value of warning for each site
  geom_hline(aes(yintercept = warning), linetype = "dashed")+
  geom_hline(aes(yintercept = alarm), linetype = "dashed")+
  facet_wrap(~site)+
  theme_bw(base_size = 24)+
  scale_color_manual(values = c("#fb1100","#ffa99e", "orange", "black"))+
  #rename the legend to "Turbidity Trigger" and ylab to "Turbidity (NTU)"
  labs(color = "Turbidity Trigger",
       y = "Turbidity (NTU)")+
  # make the title "Turbidity Triggers for ELC, Timberline, Archery, and Legacy"
  ggtitle("Turbidity Triggers for ELC, Timberline, Archery, and Legacy")+
  # include the month and year in the x axis labels
  scale_x_datetime(date_labels = "%m/%Y", date_breaks = "6 month")

 ggsave(filename = "data/sharing/threshold_calc/turb_warning_alarm_graph_test.jpg", width = 30, height = 14, dpi = 300)
 
 

```


