---
title: "02_exploring_data"
author: "Katie Willi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("src/package_loader.R")
lapply(c("data.table", "tidyverse", "rvest", "readxl", "lubridate", "zoo", "padr","plotly", "feather", "RcppRoll", "yaml", "ggpubr", "profvis", "janitor"), package_loader)

sapply(list.files("src/qaqc/explore_and_fix_fxns/verification_functions", pattern = "*.R", full.names = TRUE), source, .GlobalEnv)

sapply(list.files("src/qaqc/explore_and_fix_fxns/plotting_functions", pattern = "*.R", full.names = TRUE), source, .GlobalEnv)
```

#### Add verification column
```{r}
all_data_flagged <- readRDS('data/flagged/all_data_flagged.RDS')
verify_all_data_flagged <- map(all_data_flagged, add_verification_column)
```

#### Generate flag report
```{r}
flag_report <- map(verify_all_data_flagged, generate_flag_report) %>%
  bind_rows()

saveRDS(flag_report, 'data/flag_report.RDS')
write_csv(flag_report, 'data/flag_report.csv')
```

#### Visualize the flags
```{r}
# Current vis:
plotly_plot <- plotly::ggplotly(ggplot() +
  geom_point(data = filter(verify_all_data_flagged[["archery-Temperature"]], is.na(flag)), 
             aes(x=DT_round, y = mean)) +
  geom_point(data = filter(verify_all_data_flagged[["archery-Temperature"]], !is.na(flag)), 
             aes(x=DT_round, y = mean, color = flag)) +
  theme_bw() +
  theme(legend.position = 'bottom') +
  facet_wrap(~year, scales = "free_x"))
```

Visualizing daily plots
```{r, fig.width=12, fig.height=7}
# generate_daily_flag_plots("archery", "Temperature", "missing data", df_list = verify_all_data_flagged)
```

Visualizing weekly plots
```{r, fig.width=12, fig.height=7}
# generate_weekly_flag_plots("archery", "Temperature", "slope violation", df_list = verify_all_data_flagged)
```

Stack the weekly and daily plots
```{r, fig.width=12, fig.height=12}
# stack_flag_plots("archery", "Temperature", "missing data", verify_all_data_flagged)
```

Histograms of all parameter/site combos
```{r}
# making histograms for temperatures
## pulling all the temperature dfs from the all_data list

# temperature_hist_list <- verify_all_data_flagged[grep("Temperature", names(all_data_summary_list), ignore.case = TRUE)]

## use imap to use the index in the list for the plot titles
## (not loving imap, if there is a better way to do this please change this)

# temperature_hist_plots <- imap(temperature_hist_list, ~generate_general_histogram(.x, .y))
# temperature_hist_plots

## How to pull the histogram data that ggplot generates to make histograms
# temperature_hist_data <- map(temperature_hist_plots, ~ ggplot_build(.x)$data[[1]]) 
```

```{r}
# imap(verify_all_data_flagged, ~generate_seasonal_histogram(.x, .y))

# output_dir <- "/Users/juandlt_csu/Library/CloudStorage/OneDrive-Colostate/poudre_sonde_network/data/histogram_images"
# 
# # Use imap to iterate over the list and generate/save plots
# imap(verify_all_data_flagged, ~{
#   df_name <- .y  # Get the name of the data frame
#   plot <- generate_seasonal_histogram(.x, .y)  # Generate the plot
# 
#   # Create a filename based on the name of the data frame
#   filename <- file.path(output_dir, paste0(df_name, ".png"))
# 
#   # Save the plot as an image (you can adjust the file format and options)
#   ggsave(filename, plot, device = "png", width = 8, height = 6)
# })
```

# Is the seasonal threshold flag doing anything useful?

```{r}
all_data <- verify_all_data_flagged %>% bind_rows() %>%
  filter(parameter %in% c("Actual Conductivity", "Chl-a Fluorescence", "DO", "External Voltage", 
     "FDOM Fluorescence", "ORP", "pH", "Specific Conductivity", "Temperature", "Turbidity"))

outside_range <- all_data %>% 
  filter(flag %in% c("outside of seasonal range"))

generate_weekly_flag_plots <-


generate_weekly_flag_plots <- function(site_arg, parameter_arg, flag_arg = "outside of seasonal range", df_list) {

  site_param <- paste0(site_arg, "-", parameter_arg)

  site_flag_dates <- df_list[[site_param]]

  if (!is.null(site_flag_dates)){
    # vector of sites in the order that they are in spatially
    # some sites have some funkiness going on
    sites_order <- c("tamasag", # rist
                     "legacy",
                     "lincoln",
                     "timberline",
                     "prospect",
                     "boxelder", # elc
                     "archery",
                     "river bluffs")
    # determining the index for the site of interest.
    site_index <- which(sites_order == site_arg)

    # Generating df name to pull from df_list list
    site_param <- paste0(site_arg, "-", parameter_arg)
    # filter for all the days that are tagged within the site-param df of interest
    site_flag_dates <- site_flag_dates %>%
      filter(if (is.null(flag_arg)) !is.na(flag) else (flag == flag_arg)) %>%
      group_by(day(DT_join), month, year) %>%
      slice(1)

    if (nrow(site_flag_dates > 0)) {
      # This for loop generates an overlayed plot of weekly data for the site of
      # interest sandwiched by the site above and below it for each day that was
      # tagged by a flag of interest
      plot_list <- list()

      for(i in 1:nrow(site_flag_dates)) {

        flag_title <- site_flag_dates$flag[i]
        flag_year <- site_flag_dates$year[i]
        flag_month <- site_flag_dates$month[i]
        flag_day <- site_flag_dates$DT_round[i]
        # Getting the prior and subsequent 3 days to the flag day
        start_day <- flag_day - days(3)
        end_day <- flag_day + days(3)

        # filtering dfs of interest for the weeks where a flag was detected
        site_df <- df_list[[site_param]] %>%
          filter(year == flag_year,
                 month == flag_month,
                 DT_round >= start_day & DT_round <= end_day)

        # TryCatch used here to avoid erroring out on the first and last values of
        # sites_order object (there is no prior/next record after the first/last record).
        # Return df as NULL in case of an error
        prev_site_df <- NULL
        next_site_df <- NULL

        tryCatch({
          previous_site <- paste0(sites_order[site_index-1],"-",parameter_arg)
          prev_site_df <- df_list[[previous_site]] %>%
            filter(year == flag_year,
                   month == flag_month,
                   DT_round >= start_day & DT_round <= end_day)},
          error = function(err) {
            cat("No previous site.\n")})

        tryCatch({
          next_site <- paste0(sites_order[site_index+1],"-",parameter_arg)
          next_site_df <- df_list[[next_site]] %>%
            filter(year == flag_year,
                   month == flag_month,
                   DT_round >= start_day & DT_round <= end_day)},
          error = function(err) {
            cat("No next site.\n")})

        # Bind all three dfs
        week_plot_data <- list(site_df, prev_site_df, next_site_df) %>%
          # remove NULL values from the list
          keep(~ !is.null(.)) %>%
          bind_rows()

        # Using the data from the day where a flag was detected to generate a window
        # to easily distinguish the data of interest in comparison with the rest of
        # the data
        site_day_data <- df_list[[site_param]] %>%
          filter(year == flag_year,
                 month == flag_month,
                 day(DT_round) == day(flag_day))

        y_min <- site_day_data$m_mean01[i]
        y_max <- site_day_data$m_mean99[i]
        # there is a join somewhere that adds two site and parameter cols
        # need to find it and fix that
        week_plot <- ggplot(data = week_plot_data, aes(x=DT_round, y=mean, color=site)) +
          geom_rect(data = site_day_data, aes(xmin = min(DT_round), xmax = max(DT_round),
                                              ymin = -Inf, ymax = Inf),
                    fill = "grey",
                    alpha = 0.01,
                    color = NA) +
          geom_line() +
          geom_hline(yintercept = y_min, color = "red") +
          geom_hline(yintercept = y_max, color = "red") +
          theme_bw() +
          theme(legend.position = 'bottom') +
          ggtitle(paste(flag_arg,"at", site_arg, "on", as.character(flag_day))) +
          labs(x = "Datetime",
               y = "Mean")

        plot_list[[paste(site_param, as.character(flag_day))]] <- week_plot

        sorted_plot_names <- names(plot_list)[order(names(plot_list))]

        plot_list <- plot_list[sorted_plot_names]
      }
      return(plot_list)
    } else {
      return(paste(flag_arg, "not detected.\n"))
    }
  } else {
    return(paste(site_arg, parameter_arg, "combination not available.\n"))
  }
}

```




