#' Process and Stitch Final Corrections
#'
#' @description
#' Iterates through user choices for each drift window, applies the chosen mathematical
#' corrections or special data flags, and cleans up remaining out-of-bounds flags.
#'
#' @param df_scenarios Dataframe. Generated by \code{generate_scenario_grid.R}.
#' @param windows_df Dataframe. Contains user-selected strategy parameters for each window block.
#'
#' @details
#' \itemize{
#'   \item Iterates chronologically through every validated window block provided in \code{windows_df}.
#'   \item Applies special strategies: Sets data points to missing (\code{NA}) and flags metadata as \code{"OMIT"} for \code{"non_resolved"} fields, or drops the drift tracking flag if set to \code{"unflag"}.
#'   \item Applies analytical strategies: Maps math scenarios (\emph{linear, exponential, etc.}) to their matching calculation column, stitching those corrected segments into a final values column.
#'   \item Scans for any data rows residing \emph{outside} active window zones that remain flagged as raw drift, stripping those tokens away and setting statuses to \code{"PASS"}.
#'   \item Drops all alternative transformation grid columns to clean up schema bloating.
#' }
#'
#' @return A finalized dataframe featuring modified time-series streams (\code{mean_analysis}, \code{mean_drift_trans})
#' and up-to-date data quality flags (\code{user_flag}, \code{drift}, \code{verification_status}, \code{final_status})
#' ready for saving to `post_verification` folder.
stitch_final_corrections <- function(df_scenarios, windows_df) {
  df_final <- df_scenarios %>%
    mutate(mean_drift_trans = mean_analysis, correction_type = "raw")

  in_any_verified_window <- rep(FALSE, nrow(df_final))

  for (i in seq_len(nrow(windows_df))) {
      s_dt   <- windows_df$start_dt[i]
      e_dt   <- windows_df$end_dt[i]
      d_type <- windows_df$arg_drift_type[i]
      corr_type <- windows_df$arg_correction_type[i]

      in_window <- df_final$DT_round >= s_dt & df_final$DT_round <= e_dt
      in_any_verified_window <- in_any_verified_window | in_window

      if (d_type == "non_resolved") {
        # Mark data as missing and flag status tracks as OMIT
        df_final$mean_analysis[in_window]     <- NA_real_
        df_final$mean_drift_trans[in_window]  <- NA_real_
        df_final$correction_type[in_window]   <- "non_resolved"
        df_final$verification_status[in_window] <- "OMIT"
        df_final$final_status[in_window]        <- "OMIT"
        df_final$pre_post_source[in_window]          <- NA_real_
      } else if( d_type == "unflag" ){
        # user selected "unflag" for a window,
        #remove the drift token from user_flag and set drift to FALSE
        #PASS data if there are no remaining flags
        df_final$mean_drift_trans[in_window] <- df_final$mean_analysis[in_window]
        df_final$correction_type[in_window]  <- "raw"
        df_final$pre_post_source[in_window]          <- NA_real_
        df_final$user_flag[in_window] <- map_chr(df_final$user_flag[in_window], remove_drift_token)
        df_final$drift[in_window] <- FALSE
        df_final$verification_status[in_window] <- if_else(is.na(df_final$user_flag[in_window]) & df_final$verification_status[in_window] != "OMIT", "PASS", df_final$verification_status[in_window])
        df_final$final_status[in_window]        <- if_else(is.na(df_final$user_flag[in_window]) & df_final$final_status[in_window] != "OMIT", "PASS", df_final$final_status[in_window])

      }else {
        #based on user selection, determine which column to use for the final mean_drift_trans
        val_column <- case_when(
          d_type == "linear" & corr_type == "multiplicative"        ~ "linear_mult",
          d_type == "linear" & corr_type == "additive"              ~ "linear_add",
          d_type == "exponential" & corr_type == "multiplicative"  ~ "exp_mult",
          d_type == "exponential" & corr_type == "additive"        ~ "exp_add",
          d_type == "uniform"     & corr_type == "multiplicative"  ~ "uniform_mult",
          d_type == "uniform"     & corr_type == "additive"        ~ "uniform_add",
          d_type == "fitted_linear" & corr_type == "multiplicative" ~ "fitted_mult",
          d_type == "fitted_linear" & corr_type == "additive"       ~ "fitted_add",
          TRUE                      ~ "mean_analysis"
        )

        if (d_type %in% c("linear", "exponential", "uniform", "fitted_linear")) {
          df_final$mean_drift_trans[in_window] <- df_final[[val_column]][in_window]
          df_final$correction_type[in_window]  <- d_type
        }
      }
    }

    outside_unverified_drift <- df_final$drift & !in_any_verified_window
    # if the data is outside a verified window and is flagged as drift, remove the drift token and set the verification_status and final_status to PASS if user_flag is NA

    if (any(outside_unverified_drift)) {
      df_final <- df_final %>%
        mutate(
          user_flag = if_else(outside_unverified_drift, map_chr(user_flag, remove_drift_token), user_flag),
          drift = if_else(outside_unverified_drift, FALSE, drift),
          verification_status = if_else(outside_unverified_drift & is.na(user_flag) & verification_status != "OMIT", "PASS", verification_status),
          final_status        = if_else(outside_unverified_drift & is.na(user_flag) & final_status != "OMIT", "PASS", final_status)
        )
    }
    # Remove Temporary Scenario Columns Before Export
    df_final <- df_final %>%
      select(-any_of(c("linear_add", "linear_mult", "exp_add", "exp_mult",
                       "uniform_add", "uniform_mult", "fitted_add", "fitted_mult")))

  return(df_final)
}
