---
output: word_document
---

```{r setup, include=FALSE, echo=FALSE}
###### ------ MONTH AND YEAR SELECTOR ------ ######
dir <- getwd()
month_select <- 11
year_select <- 2025

#### ------ Run lines above to set month and year ------ ####

# this does not work with getwd() for whatever reason, may trouble shoot later
# input_filename <- paste0(dir, "/poudre_sonde_network/02_pwqn_report_gen.Rmd")
# output_filename <- paste0(dir, "/poudre_sonde_network/budget_summary_", month_select, '_', year_select, '.docx' )
#rmarkdown::render(input = input_filename, output_file = output_filename)

# RUN LINE BELOW IN CONSOLE TO  get the correct file name to change after knitting
# paste0("budget_summary_", month_select, '_', year_select)


```

# PWQN Summary of Work for `r paste(month_select, "/", year_select)`

Prepared by: ROSSyndicate - Sam Struthers

`r Sys.Date()`

## General Outline of Work for `r paste(month_select, "/", year_select)`

-   1

-   2

```{r import, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# set dir for downstream uses
dir <- getwd()
package_loader <- function(x) {
  if (x %in% installed.packages()) {
    library(x, character.only = TRUE)
  } else {
    install.packages(x)
    library(x, character.only = TRUE)
  }
}
lapply(c("tidyverse", "readxl", "arrow", "flextable", "officer", "here"), package_loader)


# read in data created by 01_pwqn_data_prep.Rmd
all_data <- read_csv(paste0(dir, "/docs/pwqn/docs/monthly_budget/charges_final/charges_final_", month_select, "_", year_select,  ".csv"), show_col_types = FALSE)

  # calculate totals
final_summary <- tibble(`Hours x Rate (if applicable)` = c("Total CSU Contribution: ",
                                                           "Total (excluding CSU cont.)"), 
                        Cost = c(sum(all_data$Cost[all_data$include == "No"]),
                                 sum(all_data$Cost[all_data$include != "No"])), 
                        include = c("No", "Yes"))

final <- all_data%>%
  bind_rows(final_summary)

field_summary <- read_csv(paste0(dir, "/docs/pwqn/docs/monthly_budget/field_summary/field_summary_",month_select, "_", year_select,".csv"), show_col_types = FALSE)


```

```{r print, echo=FALSE, message=FALSE}
 

#create standard border color and width
std_border <- fp_border_default(width = 1, color = "black")
set_flextable_defaults(theme_fun = "theme_box", na_string = "" )
  
#create table of costs 
flextable(final, col_keys = c("Category","Staff or Vendor","Description",
                                        "Hours x Rate (if applicable)",  "Cost"))%>%
  # italicize in kind contributions
  italic( i = ~ include == "No", j = "Cost" )%>%
  #bold total cost
  bold( i = nrow(final))%>%
  #color in kind contributions red
  #color( i = ~ include == "In Kind", j = "Cost", color = "red")%>%
  #merge categories 
  merge_v( j = ~Category )%>%
  #merge total NA rows
   merge_h( i = nrow(final)-1 )%>%
   merge_h( i = nrow(final))%>%
   # set caption and table width
  set_caption(caption = paste0("Summary of ", month_select,"/",year_select, " PWQN costs. Italics denote contributions from CSU"))%>%
  set_table_properties( width = 1, layout = "autofit")

```

## Summary of site visits for `r paste(month_select, "/", year_select)`

```{r field_summary, echo=FALSE, message=FALSE}

if(sum(field_summary$`Site Visits`) > 0){

flextable(field_summary)%>%

  #set table widths

  set_table_properties( width = 1, layout = "autofit")  
}


```

## Data Summary for `r paste(month_select, "/", year_select)`

