```{r}
library(tidyverse)
```

```{r}
# set data directory paths
all_path <- here("data", "virridy_verification", "all_data_directory")
pre_verification_path <- here("data", "virridy_verification", "pre_verification_directory")
intermediary_path <- here("data", "virridy_verification", "intermediary_directory")
verified_path <- here("data", "virridy_verification", "verified_directory")
```

```{r}
flagged_data <- read_rds(here("data","virridy_verification","all_data_flagged_complete.RDS"))

pre_processed_data <- map(.x = flagged_data, \(x)
  x %>% 
    mutate(
      mean_verified = NA, # if verification status pass, this is mean
      is_verified = FALSE, # whether or not the data has been verified
      verification_status = NA, # can only be pass/fail/skip 
      week = week(DT_round), 
      weekday = wday(DT_round, week_start = 7),
      y_w = paste(year, "-", week),
      day = yday(DT_round),
      y_d = paste(year, "-", day)
      )
)
```

Now we will move the pre-processed flagged data into the pending review directory
```{r}
iwalk(pre_processed_data, \(x, idx)
      saveRDS(x, here(all_path, idx))
      )

R.utils::copyDirectory(all_path, pre_verification_path)
```

```{r}
rm(list = c("flagged_data", "pre_processed_data"))
```

