```{r set up}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, functions, and all flagged data}
# Load necessary libraries
library(tidyverse)
library(ggpubr)
library(here)

# set function directory paths
fxn_path <- here("src")

# Source functions
invisible(map(
  list.files(fxn_path, pattern = "*.R", full.names = TRUE),
  ~ source(.x, echo = FALSE)
))

# set data directory paths
all_path <- here("data", "virridy_verification", "all_data_directory")
pre_verification_path <- here("data", "virridy_verification", "pre_verification_directory")
intermediary_path <- here("data", "virridy_verification", "intermediary_directory")
verified_path <- here("data", "virridy_verification", "verified_directory")
  
# Load all flagged data
all_data <- set_names(map(list.files(all_path, full.names = TRUE), read_rds), list.files(all_path))

# Load all intermediary data
intermediary_data <- set_names(map(list.files(intermediary_path, full.names = TRUE), read_rds), list.files(intermediary_path))

# Load all verified data
verified_data <- set_names(map(list.files(verified_path, full.names = TRUE), read_rds), list.files(verified_path))
```

```{r working data selection}
# Prompt user to select data for verification
get_working_data_decision()
```

```{r set site and parameter variables}
network <- "virridy"
# Set the site and parameter to verify
site <- "archery"
parameter <- "Chl-a Fluorescence"
```

If you get the error 'Error in !updated_df$is_verified : invalid argument type', it means that the site-parameter dataframe does not exist in the data. Please check the spelling of the site or parameter and make sure the data exists.

```{r set the site-param df to update}
# Initialize the site-parameter dataframe to be updated
site_param_name <- paste0(site, "-", parameter)

tryCatch({
  updated_site_param_df <- working_data[[site_param_name]]
}, error = function(e) {
  error_message <- paste0("Error: '", site_param_name, "' not found in the data.\n",
                          "Please check the spelling of the site or parameter and make sure the data exists.")
  stop(error_message, call. = FALSE)
})

# Save the updated site-parameter dataframe to the intermediary directory
save_intermediary_dir(updated_df = updated_site_param_df, df_name = site_param_name)
```

```{r generate the initial weekly plot objects, warning=FALSE}
# Generate initial weekly plot objects
weekly_plot_objects <- generate_initial_weekly_plots(
  all_df_list = all_data,
  pending_df_list = working_data, 
  site_arg = site,
  parameter_arg = parameter,
  flag_arg = NULL
)
QUIT <- FALSE
```
