---
title: "PWQN QAQC Presentation Figure Generation"
author: "Katie Willi"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
source("src/package_loader.R")
lapply(c("tidyverse", "feather", "data.table", "ggpubr"), package_loader)

# Source most recent flagging data
all_data_flagged <- readRDS("data/flagged/all_data_flagged.RDS") 
```

```{r}
# This is not quite working the way it should - Trying to determine how much of the data per site-parameter combo is flagged, AFTER removing NA/sonde not employed data. 
summ_flag <- read_feather('data/flagged/all_data_flagged.feather') %>%
  data.table() %>%
  filter(month %in% c(5, 6, 7, 8, 9, 10, 11)) %>%
  mutate(yn_flag = ifelse(grepl("site visit|sv window|slope violation|repeated value|outside of seasonal range|outside sd range|outside of sensor specification range|suspect data", cleaner_flag), "flag", 
                ifelse(grepl("missing data|sonde not employed", cleaner_flag), "no flag", "no flag"))) %>%
  dplyr::group_by(site, parameter, yn_flag) %>%
  dplyr::summarize(total = n()) %>%
  ungroup() %>%
  group_by(site, parameter) %>%
  mutate(percentage_not_flagged = ifelse(yn_flag == "flag", total / sum(total) * 100, 0))
```

```{r}
color_code <- tibble(flag = c("missing data", "sonde not employed", 
                              "site visit", "sv window", 
                              "slope violation", "repeated value", 
                              "outside of seasonal range", "outside sd range", 
                              "outside of sensor specification range", "suspect data"),
                     color = c("grey", "black",
                               "#FFBA00", "#FFBA00",
                               "#002FA7", "#7DF365",
                               "#D55E00", "#1C7C54", 
                               "#FF69B4", "#bdcffc"))


color_joiner <-function(data, flag_type) {
  
  data %>%
    filter(grepl(flag_type, flag)) %>%
    mutate(flag = flag_type) %>%
    left_join(color_code, by = "flag")
  
}  

# plot raw values without flags:
simp_plotter <- function(clean = FALSE, start_date = "2023-04-11 00:00:00", 
                    end_date ="2023-04-18 00:00:00", site = "river bluffs", 
                    parameter = "DO", title = "River Bluffs Dissolved Oxygen", units = "mg/L"){
  
  flag_start_date <- ymd_hms(start_date)
  flag_end_date <- ymd_hms(end_date)
  flag_plot_data <- all_data_flagged[[paste0(site, "-", parameter)]] %>% 
    filter(DT_round >= flag_start_date & DT_round <= flag_end_date)
  
  if(clean == TRUE) {
    flag_plot_data$flag <- flag_plot_data$cleaner_flag
  }
  
  y_min <- flag_plot_data$t_mean01[1]
  y_max <- flag_plot_data$t_mean99[1]
  
  ggplot() +
    geom_point(data = flag_plot_data, 
               aes(x = DT_round, y = mean), color = "grey", size = 2) +
    labs(x = "Date-time",
         y = paste(units)) +
    ggtitle(paste(title)) +
    ylim(y_min, y_max) +
    theme_classic()
  
}

# function to view flagging, with and without network check:
plotter <- function(clean = FALSE, start_date = "2023-04-11 00:00:00", 
                    end_date ="2023-04-18 00:00:00", site = "river bluffs", 
                    parameter = "DO", title = "River Bluffs Dissolved Oxygen", units = "mg/L"){
  
  flag_start_date <- ymd_hms(start_date)
  flag_end_date <- ymd_hms(end_date)
  flag_plot_data <- all_data_flagged[[paste0(site, "-", parameter)]] %>% 
    filter(DT_round >= flag_start_date & DT_round <= flag_end_date)
  
  if(clean == TRUE) {
    flag_plot_data$flag <- flag_plot_data$cleaner_flag
  }
  
  #missing <- color_joiner(data = flag_plot_data, flag_type = "missing data")
  slope_violation <- color_joiner(data = flag_plot_data, flag_type = "slope violation")
  repeated_value <- color_joiner(data = flag_plot_data, flag_type = "repeated value")
  seasonal_range <- color_joiner(data = flag_plot_data, flag_type = "outside of seasonal range")
  site_visit <- color_joiner(data = flag_plot_data, flag_type = "site visit")
  site_visit <- rbind(site_visit, color_joiner(data = flag_plot_data, flag_type = "sv window"))
  sonde_not_employed <- color_joiner(data = flag_plot_data, flag_type = "sonde not employed")
  suspect_data <- color_joiner(data = flag_plot_data, flag_type = "suspect data")
  sd_range <- color_joiner(data = flag_plot_data, flag_type = "outside sd range")
  
  
  y_min <- flag_plot_data$t_mean01[1]
  y_max <- flag_plot_data$t_mean99[1]
  
  ggplot() +
    geom_point(data = flag_plot_data, 
               aes(x = DT_round, y = mean), color = "grey", size = 2) +
    geom_point(data = suspect_data,
               aes(x = DT_round, y = mean), pch=21, color = "white",
               fill = unique(suspect_data$color), size = 4) +
    geom_point(data = seasonal_range, 
               aes(x = DT_round, y = mean), pch=21, color = "white", 
               fill = unique(seasonal_range$color), size = 4) +
    geom_point(data = repeated_value, 
               aes(x = DT_round, y = mean), pch=21, color = "white", 
               fill = unique(repeated_value$color), size = 4) +
    geom_point(data = sd_range, 
               aes(x = DT_round, y = mean), pch=21, color = "white", 
               fill = unique(sd_range$color), size = 4) +
    geom_point(data = slope_violation,
               aes(x = DT_round, y = mean), pch=21, color = "white", 
               fill = unique(slope_violation$color), size = 4) +
    geom_point(data = site_visit,
               aes(x = DT_round, y = mean), pch=21, color = "white", 
               fill = unique(site_visit$color), size = 4) +
    geom_point(data = sonde_not_employed, 
               aes(x = DT_round, y = mean), pch=21, color = "white", 
               fill = unique(sonde_not_employed$color), size = 4) +
    labs(x = "Date-time",
         y = paste(units)) +
    ylim(y_min, y_max) +
    ggtitle(paste(title)) +
    theme_classic()
  
}

# filerting out flagged data:

final_raw_plotter <- function(clean = FALSE, start_date = "2023-04-11 00:00:00", 
                    end_date ="2023-04-18 00:00:00", site = "river bluffs", 
                    parameter = "DO", title = "River Bluffs Dissolved Oxygen", units = "mg/L"){
  
  flag_start_date <- ymd_hms(start_date)
  flag_end_date <- ymd_hms(end_date)
  flag_plot_data <- all_data_flagged[[paste0(site, "-", parameter)]] %>% 
    filter(DT_round >= flag_start_date & DT_round <= flag_end_date) %>%
    filter(is.na(cleaner_flag))
  
  if(clean == TRUE) {
    flag_plot_data$flag <- flag_plot_data$cleaner_flag
  }
  
  y_min <- flag_plot_data$t_mean01[1]
  y_max <- flag_plot_data$t_mean99[1]
  
  ggplot() +
    geom_point(data = flag_plot_data, 
               aes(x = DT_round, y = mean), color = "grey", size = 2) +
    labs(x = "Date-time",
         y = paste(units)) +
    ggtitle(paste(title)) +
    ylim(y_min, y_max) +
    theme_classic()
  
}


# post flag removal, hourly averaged data:
final_hour_plotter <- function(clean = FALSE, start_date = "2023-04-11 00:00:00", 
                    end_date ="2023-04-18 00:00:00", site = "river bluffs", 
                    parameter = "DO", title = "River Bluffs Dissolved Oxygen", units = "mg/L"){
  
  flag_start_date <- ymd_hms(start_date)
  flag_end_date <- ymd_hms(end_date)
  flag_plot_data <- all_data_flagged[[paste0(site, "-", parameter)]] %>% 
    filter(DT_round >= flag_start_date & DT_round <= flag_end_date) %>%
    filter(is.na(cleaner_flag)) %>%
    group_by(DT_round = floor_date(DT_round, unit = "hour"),
             t_mean01, t_mean99) %>% 
    summarize(mean = median(mean, na.rm = TRUE)) %>% 
    ungroup()

  y_min <- flag_plot_data$t_mean01[1]
  y_max <- flag_plot_data$t_mean99[1]
  
  ggplot() +
    geom_point(data = flag_plot_data, 
               aes(x = DT_round, y = mean), color = "grey", size = 2) +
    labs(x = "Date time",
         y = paste(units)) +
    ggtitle(paste(title)) +
    ylim(y_min, y_max) +
    theme_classic()
  
}
```

Timberline and Prospect Sp Conductivity flagging, without flagging, clean flags, etc. 

```{r}
bad_timb = plotter(clean = F, start_date = "2022-08-01 08:30:00", end_date = "2022-08-08 09:30:00", site = "timberline", parameter = "Specific Conductivity", title = "Timberline Sp. Conductivity", units = "uS/cm")
good_timb = plotter(clean = T, start_date = "2022-08-01 08:30:00", end_date = "2022-08-08 09:30:00", site = "timberline", parameter = "Specific Conductivity", title = "Timberline Sp. Conductivity", units = "uS/cm")
bad_pros =plotter(clean = F, start_date = "2022-08-01 08:30:00", end_date = "2022-08-08 09:30:00", site = "prospect", parameter = "Specific Conductivity", title = "Prospect Sp. Conductivity", units = "uS/cm")
good_pros =plotter(clean = T, start_date = "2022-08-01 08:30:00", end_date = "2022-08-08 09:30:00", site = "prospect", parameter = "Specific Conductivity", title = "Prospect Sp. Conductivity", units = "uS/cm")

ggarrange(bad_timb, bad_pros, nrow = 2)
ggsave(filename = 'scratch/reporting/bad_flags.png',
       width = 7, height = 6.47)

ggarrange(good_timb, good_pros, nrow = 2)
ggsave(filename = 'scratch/reporting/good_flags.png',
       width = 7, height = 6.47)
 
simp_timb = simp_plotter(clean = F, start_date = "2022-08-01 08:30:00", end_date = "2022-08-08 09:30:00", site = "timberline", parameter = "Specific Conductivity", title = "Timberline Sp. Conductivity", units = "uS/cm")
simp_pros = simp_plotter(clean = F, start_date = "2022-08-01 08:30:00", end_date = "2022-08-08 09:30:00", site = "prospect", parameter = "Specific Conductivity", title = "Prospect Sp. Conductivity", units = "uS/cm")

ggarrange(simp_timb, simp_pros, nrow = 2)
ggsave(filename = 'scratch/reporting/no_flags.png',
       width = 7, height = 6.47)


# Plotting 15-minute data after removal of flags:
fin_timb = final_raw_plotter(clean = F, start_date = "2022-08-01 08:30:00", end_date = "2022-08-08 09:30:00", site = "timberline", parameter = "Specific Conductivity", title = "Timberline Sp. Conductivity", units = "uS/cm")
fin_pros = final_raw_plotter(clean = F, start_date = "2022-08-01 08:30:00", end_date = "2022-08-08 09:30:00", site = "prospect", parameter = "Specific Conductivity", title = "Prospect Sp. Conductivity", units = "uS/cm")

ggarrange(fin_timb, fin_pros, nrow = 2)
ggsave(filename = 'scratch/reporting/final_raw_flags.png',
       width = 7, height = 6.47)

hourly_timb = final_hour_plotter(clean = F, start_date = "2022-08-01 08:30:00", end_date = "2022-08-08 09:30:00", site = "timberline", parameter = "Specific Conductivity", title = "Timberline Sp. Conductivity", units = "uS/cm")
hourly_pros = final_hour_plotter(clean = F, start_date = "2022-08-01 08:30:00", end_date = "2022-08-08 09:30:00", site = "prospect", parameter = "Specific Conductivity", title = "Prospect Sp. Conductivity", units = "uS/cm")

ggarrange(hourly_timb, hourly_pros, nrow = 2)
# ggsave(filename = 'scratch/reporting/final_hour_flags.png',
#        width = 7, height = 6.47)
```

# River Bluffs example - QAQC start to finish

```{r}
simp_plotter() #%>% ggsave(filename = 'scratch/reporting/rivbufraw.png',width = 8, height = 6.47)
plotter(clean = TRUE) #%>% ggsave(filename = 'scratch/reporting/rivbufflag.png', width = 8, height = 6.47)
final_raw_plotter() #%>% ggsave(filename = 'scratch/reporting/rivbufffin.png',width = 8, height = 6.47)
final_hour_plotter() #%>% ggsave(filename = 'scratch/reporting/rivbuffinhour.png', width = 8, height = 6.47)
```

# Turbidity example (appendix plot)

```{r}
start_date = "2022-10-11 00:00:00"
end_date = "2022-10-14 23:00:00"

turb_plotter <- function(clean = FALSE, start_date = "2023-04-11 00:00:00", 
                    end_date ="2023-04-18 00:00:00", site = "river bluffs", 
                    parameter = "DO", title = "River Bluffs Dissolved Oxygen", units = "mg/L"){
  
  flag_start_date <- ymd_hms(start_date)
  flag_end_date <- ymd_hms(end_date)
  flag_plot_data <- all_data_flagged[[paste0(site, "-", parameter)]] %>% 
    filter(DT_round >= flag_start_date & DT_round <= flag_end_date)
  
  if(clean == TRUE) {
    flag_plot_data$flag <- flag_plot_data$cleaner_flag
  }
  
  #missing <- color_joiner(data = flag_plot_data, flag_type = "missing data")
  slope_violation <- color_joiner(data = flag_plot_data, flag_type = "slope violation")
  repeated_value <- color_joiner(data = flag_plot_data, flag_type = "repeated value")
  seasonal_range <- color_joiner(data = flag_plot_data, flag_type = "outside of seasonal range")
  site_visit <- color_joiner(data = flag_plot_data, flag_type = "site visit")
  site_visit <- rbind(site_visit, color_joiner(data = flag_plot_data, flag_type = "sv window"))
  sonde_not_employed <- color_joiner(data = flag_plot_data, flag_type = "sonde not employed")
  suspect_data <- color_joiner(data = flag_plot_data, flag_type = "suspect data")
  sd_range <- color_joiner(data = flag_plot_data, flag_type = "outside sd range")
  
  ggplot() +
    geom_point(data = flag_plot_data, 
               aes(x = DT_round, y = mean), color = "grey", size = 2) +
     geom_point(data = slope_violation,
              aes(x = DT_round, y = mean), pch=21, color = "white",
               fill = unique(slope_violation$color), size = 4) +
    geom_point(data = site_visit,
               aes(x = DT_round, y = mean), pch=21, color = "white", 
               fill = unique(site_visit$color), size = 4) +
    geom_point(data = sonde_not_employed, 
               aes(x = DT_round, y = mean), pch=21, color = "white", 
               fill = unique(sonde_not_employed$color), size = 4) +
    labs(x = "Date-time",
         y = paste(units)) +
    ylim(0, 100) +
    ggtitle(paste(title)) +
    theme_classic()
  
}

t1 = turb_plotter(clean = TRUE, site = "timberline", parameter = "Turbidity", start_date =  start_date, end_date = end_date, title = "Timberline Turbidity", units = "NTU")
p1 = turb_plotter(clean = TRUE, site = "prospect", parameter = "Turbidity", start_date =  start_date, end_date = end_date, title = "Prospect Turbidity", units = "NTU")# %>% 
b1 = turb_plotter(clean = TRUE, site = "boxelder", parameter = "Turbidity", start_date =  start_date, end_date = end_date, title = "Boxelder Turbidity", units = "NTU")# %>% 

ggarrange(t1, p1, b1, nrow = 3) #%>% ggsave(filename = 'scratch/reporting/turb_problems.png', width = 13, height = 11)
```


